import type { Area, Category } from "./types";

// ---------------------------------------------------------------------------
// AREAS
// Ranked by commercial opportunity (foreign population, purchasing power,
// English-speaking demand, professional-service density). Start with these
// four, expand the matrix once the first partners are onboarded.
// ---------------------------------------------------------------------------
export const areas: Area[] = [
  {
    slug: "eixample",
    name: "Eixample",
    district: "Eixample",
    blurb:
      "Barcelona's grand 19th-century grid: wide boulevards, Gaudí landmarks like Casa Batlló and La Pedrera, and the city's business and shopping core. Home to the largest international community in Barcelona.",
    image: "/images/areas/eixample.jpg",
    imageCredit: {
      photographer: "Alhzeiia",
      license: "CC BY-SA 2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Eixample_aire_cropped.jpg",
    },
    mapCenter: { lat: 41.3931, lng: 2.1622 },
  },
  {
    slug: "poblenou",
    name: "Poblenou",
    district: "Sant Martí",
    blurb:
      "A former industrial district turned tech and creative hub, loft-style buildings, beachfront promenade, and a young international crowd. Right on the coast in Sant Martí.",
    image: "/images/areas/poblenou.jpg",
    imageCredit: {
      photographer: "Manuellebron",
      license: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:PereIV-HabitatSky.jpg",
    },
    mapCenter: { lat: 41.4036, lng: 2.1994 },
  },
  {
    slug: "sarria-sant-gervasi",
    name: "Sarrià-Sant Gervasi",
    district: "Sarrià-Sant Gervasi",
    blurb:
      "Leafy, upscale and quiet, Barcelona's most established residential district for international families, close to several of the city's international schools.",
    image: "/images/areas/sarria.jpg",
    imageCredit: {
      photographer: "Unknown, via Wikimedia Commons",
      license: "CC BY-SA 3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sarria_Seu_Districte.JPG",
    },
    mapCenter: { lat: 41.3985, lng: 2.1274 },
  },
  {
    slug: "les-corts",
    name: "Les Corts",
    district: "Les Corts",
    blurb:
      "A calm, residential district best known as home to Camp Nou, popular with international families who want good schools and private healthcare close by.",
    image: "/images/areas/les-corts.jpg",
    imageCredit: {
      photographer: "Fish-guts",
      license: "CC0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Camp_nou_2010.jpg",
    },
    mapCenter: { lat: 41.3809, lng: 2.1228 },
  },
  {
    slug: "diagonal-mar",
    name: "Diagonal Mar & Vila Olímpica",
    district: "Sant Martí",
    blurb:
      "Barcelona's modern beachfront district: marina views, high-rise apartments and the 1992 Olympic waterfront. One of the city's most international, sea-view neighbourhoods.",
    image: "/images/areas/diagonal-mar.jpg",
    imageCredit: {
      photographer: "Amadalvarez",
      license: "CC BY 3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:BCN-ParcForum-4923.jpg",
    },
    mapCenter: { lat: 41.4092, lng: 2.2160 },
  },
  {
    slug: "gracia",
    name: "Gràcia",
    district: "Gràcia",
    blurb:
      "A bohemian, village-like neighbourhood of small squares, independent shops and a strong café culture, home to one of Barcelona's largest European communities.",
    image: "/images/areas/gracia.jpg",
    imageCredit: {
      photographer: "Txllxt TxllxT",
      license: "CC BY-SA 4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Barcelona_-_Carrer_Gran_de_Gr%C3%A0cia_-_View_SE.jpg",
    },
    mapCenter: { lat: 41.4036, lng: 2.1561 },
  },
];

// ---------------------------------------------------------------------------
// CATEGORIES
// Ranked (roughly) by lead value: dentistry, legal/tax and property carry the
// highest lifetime value per referral, so they lead the list and the homepage.
// ---------------------------------------------------------------------------
export const categories: Category[] = [
  {
    slug: "dentist",
    name: "Dentist",
    pluralName: "Dentists",
    icon: "🦷",
    shortPitch: "Compare English-speaking dentists: implants, Invisalign, cosmetic dentistry and check-ups.",
    needOptions: ["Check-up / cleaning", "Invisalign / orthodontics", "Dental implants", "Cosmetic dentistry", "Emergency", "Other"],
    seoKeywords: ["dental implants", "Invisalign", "cosmetic dentist", "emergency dentist", "veneers"],
  },
  {
    slug: "lawyer",
    name: "Lawyer",
    pluralName: "Lawyers",
    icon: "⚖️",
    shortPitch: "Find an English-speaking lawyer for immigration, property, tax or family law in Barcelona.",
    needOptions: ["Immigration / visa", "Property purchase", "Tax law", "Family / divorce", "Employment", "Business setup", "Other"],
    seoKeywords: ["immigration lawyer", "property lawyer", "NIE", "TIE", "golden visa", "digital nomad visa"],
  },
  {
    slug: "property-advisor",
    name: "Property & Mortgage Advisor",
    pluralName: "Property & Mortgage Advisors",
    icon: "🏠",
    shortPitch: "English-speaking buyer's agents, mortgage brokers and property managers for Barcelona.",
    needOptions: ["Buying a property", "Mortgage advice", "Renting", "Property management", "Investment advice", "Other"],
    seoKeywords: ["buyer's agent", "mortgage broker", "relocation", "property investment", "rental agency"],
    hidden: true, // paused, not pursuing property/mortgage for now
  },
  {
    slug: "tax-advisor",
    name: "Tax Advisor",
    pluralName: "Tax Advisors",
    icon: "💶",
    shortPitch: "English-speaking gestors, accountants and tax advisors for residents and non-residents.",
    needOptions: ["Annual tax return", "Non-resident tax", "Self-employed / autónomo", "Company accounting", "Golden Visa tax planning", "Other"],
    seoKeywords: ["gestor", "non-resident tax", "autónomo", "expat tax advisor", "accountant"],
  },
  {
    slug: "dermatologist",
    name: "Dermatologist & Aesthetic Clinic",
    pluralName: "Dermatologists & Aesthetic Clinics",
    icon: "🧴",
    shortPitch: "English-speaking dermatologists and aesthetic clinics: skin checks, acne, Botox and laser treatments.",
    needOptions: ["Skin check / mole", "Acne", "Botox / fillers", "Laser hair removal", "Anti-ageing", "Other"],
    seoKeywords: ["skin check", "mole check", "Botox", "laser hair removal", "acne clinic"],
  },
  {
    slug: "doctor",
    name: "Private Doctor",
    pluralName: "Private Doctors",
    icon: "🩺",
    shortPitch: "English-speaking private GPs and specialists for residents and visitors in Barcelona.",
    needOptions: ["General check-up", "Same-day appointment", "Specialist referral", "Women's health", "Paediatrics", "Other"],
    seoKeywords: ["private GP", "family doctor", "same-day appointment", "gynaecologist", "paediatrician"],
  },
  {
    slug: "physiotherapist",
    name: "Physiotherapist",
    pluralName: "Physiotherapists",
    icon: "💪",
    shortPitch: "English-speaking physiotherapists for sports injuries, rehab and chronic pain.",
    needOptions: ["Sports injury", "Post-surgery rehab", "Back / neck pain", "Chronic pain", "Women's health physio", "Other"],
    seoKeywords: ["sports physio", "injury rehabilitation", "back pain specialist", "pelvic floor physio"],
  },
  {
    slug: "psychologist",
    name: "Psychologist & Therapist",
    pluralName: "Psychologists & Therapists",
    icon: "🧠",
    shortPitch: "English-speaking psychologists and therapists for individuals, couples and families.",
    needOptions: ["Anxiety / stress", "Couples therapy", "Family therapy", "ADHD assessment", "Trauma", "Other"],
    seoKeywords: ["anxiety therapist", "couples therapist", "ADHD assessment", "trauma therapist"],
  },
  {
    slug: "chiropractor",
    name: "Chiropractor",
    pluralName: "Chiropractors",
    icon: "🦴",
    shortPitch: "English-speaking chiropractors for back, neck and joint pain in Barcelona.",
    needOptions: ["Back pain", "Neck pain", "Sports injury", "Posture / general wellness", "Other"],
    seoKeywords: ["back pain specialist", "spinal adjustment", "sports chiropractor", "posture correction"],
  },
  {
    slug: "acupuncturist",
    name: "Acupuncturist",
    pluralName: "Acupuncturists",
    icon: "🪡",
    shortPitch: "English-speaking acupuncturists and traditional Chinese medicine practitioners in Barcelona.",
    needOptions: ["Pain relief", "Stress / anxiety", "Fertility support", "General wellness", "Other"],
    seoKeywords: ["traditional Chinese medicine", "acupuncture clinic", "fertility acupuncture", "cupping therapy"],
  },
  {
    slug: "fertility-clinic",
    name: "Fertility & IVF Clinic",
    pluralName: "Fertility & IVF Clinics",
    icon: "👶",
    shortPitch: "English-speaking fertility and IVF clinics for individuals and couples in Barcelona.",
    needOptions: ["IVF", "Egg freezing", "Fertility assessment", "Donor programs", "Other"],
    seoKeywords: ["IVF clinic", "egg freezing", "fertility treatment", "reproductive medicine"],
  },
  {
    slug: "plastic-surgeon",
    name: "Plastic & Cosmetic Surgeon",
    pluralName: "Plastic & Cosmetic Surgeons",
    icon: "💎",
    shortPitch: "English-speaking plastic and cosmetic surgeons for aesthetic procedures in Barcelona.",
    needOptions: ["Rhinoplasty", "Breast surgery", "Liposuction / body contouring", "Facial procedures", "Consultation only", "Other"],
    seoKeywords: ["rhinoplasty", "breast augmentation", "liposuction", "cosmetic surgery clinic"],
  },
  {
    slug: "lasik",
    name: "LASIK & Eye Surgery Clinic",
    pluralName: "LASIK & Eye Surgery Clinics",
    icon: "👁️",
    shortPitch: "English-speaking LASIK and laser eye surgery clinics for vision correction in Barcelona.",
    needOptions: ["LASIK consultation", "Vision correction", "Cataract surgery", "General ophthalmology", "Other"],
    seoKeywords: ["laser eye surgery", "vision correction", "cataract surgery", "ophthalmologist"],
  },
  {
    slug: "nutritionist",
    name: "Nutritionist & Dietitian",
    pluralName: "Nutritionists & Dietitians",
    icon: "🥗",
    shortPitch: "English-speaking nutritionists and dietitians for weight management, sports and clinical nutrition.",
    needOptions: ["Weight management", "Sports nutrition", "Clinical / medical diet", "General healthy eating", "Other"],
    seoKeywords: ["sports nutritionist", "weight loss", "clinical dietitian", "meal planning"],
  },
  {
    slug: "naturopath",
    name: "Naturopath",
    pluralName: "Naturopaths",
    icon: "🌿",
    shortPitch: "English-speaking naturopaths offering holistic and natural health treatments in Barcelona.",
    needOptions: ["General wellness", "Digestive health", "Hormonal balance", "Stress / fatigue", "Other"],
    seoKeywords: ["holistic medicine", "natural health", "herbal medicine", "naturopathy clinic"],
  },
  {
    slug: "holistic-doctor",
    name: "Holistic Doctor",
    pluralName: "Holistic Doctors",
    icon: "🪷",
    shortPitch: "English-speaking holistic and integrative medicine practitioners combining Chinese medicine, osteopathy, acupuncture and nutrition under one roof in Barcelona.",
    needOptions: ["Traditional Chinese Medicine", "Osteopathy", "Acupuncture", "Nutrition & diet", "General wellness consultation", "Other"],
    seoKeywords: ["traditional Chinese medicine", "integrative medicine", "holistic health centre", "Chinese herbal medicine", "craniosacral therapy"],
  },
  {
    slug: "orthodontist",
    name: "Orthodontist",
    pluralName: "Orthodontists",
    icon: "😬",
    shortPitch: "English-speaking orthodontists for Invisalign, braces and bite correction in Barcelona.",
    needOptions: ["Invisalign", "Traditional braces", "Bite correction", "Consultation only", "Other"],
    seoKeywords: ["Invisalign", "braces", "bite correction", "clear aligners"],
  },
  {
    slug: "podiatrist",
    name: "Podiatrist",
    pluralName: "Podiatrists",
    icon: "🦶",
    shortPitch: "English-speaking podiatrists for foot and ankle care in Barcelona.",
    needOptions: ["General foot care", "Ingrown toenail", "Sports injury", "Orthotics", "Other"],
    seoKeywords: ["foot doctor", "ankle specialist", "orthotics", "ingrown toenail"],
  },
  {
    slug: "eye-care",
    name: "Eye Care Specialist",
    pluralName: "Eye Care Specialists",
    icon: "👓",
    shortPitch: "English-speaking optometrists and ophthalmologists for eye exams, glasses and contact lenses in Barcelona.",
    needOptions: ["Eye exam", "Glasses / contact lenses", "Eye health concern", "Second opinion", "Other"],
    seoKeywords: ["optometrist", "ophthalmologist", "eye exam", "glasses", "contact lenses"],
  },
  {
    slug: "occupational-therapist",
    name: "Occupational Therapist",
    pluralName: "Occupational Therapists",
    icon: "🧩",
    shortPitch: "English-speaking occupational therapists for rehabilitation and daily-function support in Barcelona.",
    needOptions: ["Injury rehabilitation", "Developmental support", "Post-surgery recovery", "Workplace assessment", "Other"],
    seoKeywords: ["occupational therapy", "rehabilitation", "sensory processing", "daily living skills"],
  },
  {
    slug: "speech-therapist",
    name: "Speech Therapist",
    pluralName: "Speech Therapists",
    icon: "🗨️",
    shortPitch: "English-speaking speech and language therapists for children and adults in Barcelona.",
    needOptions: ["Child speech delay", "Bilingual development", "Adult speech therapy", "Stuttering", "Other"],
    seoKeywords: ["speech delay", "bilingual children", "language therapy", "stuttering"],
  },
  {
    slug: "insurance-broker",
    name: "Insurance Broker",
    pluralName: "Insurance Brokers",
    icon: "🛡️",
    shortPitch: "English-speaking insurance brokers for private health, home and life insurance in Barcelona.",
    needOptions: ["Private health insurance", "Home insurance", "Life insurance", "Business insurance", "Other"],
    seoKeywords: ["private health insurance", "expat insurance", "home insurance", "life insurance"],
  },
  {
    slug: "wealth-manager",
    name: "Wealth Manager & Investment Consultant",
    pluralName: "Wealth Managers & Investment Consultants",
    icon: "📈",
    shortPitch: "English-speaking wealth managers and investment consultants for expats and residents in Barcelona.",
    needOptions: ["Investment planning", "Retirement planning", "Cross-border tax planning", "Portfolio review", "Other"],
    seoKeywords: ["wealth manager", "financial advisor", "investment consultant", "pension planning"],
  },
  {
    slug: "notary",
    name: "Notary",
    pluralName: "Notaries",
    icon: "🖋️",
    shortPitch: "English-speaking notaries for property purchases and official document signings in Barcelona.",
    needOptions: ["Property purchase signing", "Power of attorney", "Document certification", "Other"],
    seoKeywords: ["notario", "property closing", "power of attorney", "document certification"],
  },
  {
    slug: "veterinarian",
    name: "Veterinarian",
    pluralName: "Veterinarians",
    icon: "🐾",
    shortPitch: "English-speaking vets for check-ups, vaccinations and emergency pet care in Barcelona.",
    needOptions: ["Check-up / vaccination", "Emergency", "Surgery", "Dental (pet)", "Other"],
    seoKeywords: ["emergency vet", "pet vaccination", "vet clinic", "animal hospital"],
  },
  {
    slug: "obgyn-midwife",
    name: "Ob-Gyn, Midwife & Doula",
    pluralName: "Ob-Gyns, Midwives & Doulas",
    icon: "🤰",
    shortPitch: "English-speaking obstetricians, gynaecologists, midwives, doulas, lactation consultants and baby sleep consultants for pregnancy, birth and the early baby months in Barcelona.",
    needOptions: ["Pregnancy care", "Birth / delivery", "Doula or birth support", "Gynaecology check-up", "Postpartum care", "Breastfeeding or lactation help", "Baby sleep support", "Fertility support", "Other"],
    seoKeywords: ["obstetrician", "gynaecologist", "midwife", "doula", "lactation consultant", "baby sleep consultant", "pregnancy doctor", "prenatal care"],
  },
  {
    slug: "pediatrician",
    name: "Pediatrician",
    pluralName: "Pediatricians",
    icon: "🧸",
    shortPitch: "English-speaking pediatricians for check-ups, vaccinations and children's health in Barcelona.",
    needOptions: ["General check-up", "Vaccinations", "Newborn care", "Urgent / sick visit", "Other"],
    seoKeywords: ["children's doctor", "newborn check-up", "vaccination schedule", "kids doctor"],
  },
  {
    slug: "osteopath",
    name: "Osteopath",
    pluralName: "Osteopaths",
    icon: "🤸",
    shortPitch: "English-speaking osteopaths for musculoskeletal pain, mobility and manual therapy in Barcelona.",
    needOptions: ["Back / neck pain", "Joint pain", "Post-injury mobility", "Pregnancy-related pain", "General wellness", "Other"],
    seoKeywords: ["osteopathy clinic", "manual therapy", "musculoskeletal pain", "cranial osteopathy"],
  },
  {
    slug: "autonomo-accountant",
    name: "Freelancer & Autónomo Accountant",
    pluralName: "Freelancer & Autónomo Accountants",
    icon: "🧾",
    shortPitch: "English-speaking accountants specifically for freelancers and autónomos: quarterly filings, invoicing and social security.",
    needOptions: ["Becoming autónomo", "Quarterly tax filings", "Invoicing setup", "Social security questions", "Annual accounts", "Other"],
    seoKeywords: ["autonomo accountant", "freelancer accounting", "quarterly VAT", "self-employed Spain"],
  },
  {
    slug: "business-lawyer",
    name: "Business Lawyer",
    pluralName: "Business Lawyers",
    icon: "🏢",
    shortPitch: "English-speaking business lawyers for company formation, contracts and corporate law in Barcelona.",
    needOptions: ["Company formation", "Contracts", "Corporate structuring", "Shareholder agreements", "Other"],
    seoKeywords: ["company formation lawyer", "SL company Spain", "corporate lawyer", "business setup"],
  },
  {
    slug: "sworn-translator",
    name: "Translator & Sworn Translator",
    pluralName: "Translators & Sworn Translators",
    icon: "📜",
    shortPitch: "English-speaking sworn (certified) translators for official documents, contracts and legal paperwork.",
    needOptions: ["Sworn/certified translation", "Document translation", "Contract translation", "Interpreting", "Other"],
    seoKeywords: ["sworn translator", "certified translation", "traductor jurado", "official document translation"],
  },
  {
    slug: "personal-trainer",
    name: "Personal Trainer",
    pluralName: "Personal Trainers",
    icon: "🏋️",
    shortPitch: "English-speaking personal trainers for 1-to-1 coaching, strength training and fitness goals in Barcelona.",
    needOptions: ["Weight loss", "Strength / muscle building", "Sports-specific training", "Post-injury / rehab fitness", "Group / small-group training", "Other"],
    seoKeywords: ["personal trainer Barcelona", "1-to-1 fitness coach", "strength coach", "english speaking gym"],
  },
  {
    slug: "driving-school",
    name: "Driving School & License Exchange",
    pluralName: "Driving Schools & License Exchange",
    icon: "🚗",
    shortPitch: "English-speaking driving schools and license-exchange gestorías in Barcelona, from full courses to converting a foreign license.",
    needOptions: ["Full course (theory + practical)", "License exchange (EU/non-EU)", "Refresher / confidence lessons", "Intensive course", "Motorcycle license", "Other"],
    seoKeywords: ["english speaking driving school Barcelona", "driving lessons in english Barcelona", "Spanish driving license exchange", "exchange foreign driving license Spain", "canje carnet de conducir Barcelona ingles", "autoescuela inglés"],
  },
  {
    slug: "family-therapist",
    name: "Family Therapist",
    pluralName: "Family Therapists",
    icon: "👨‍👩‍👧",
    shortPitch: "English-speaking family and couples therapists in Barcelona, for parenting, relationship and communication support.",
    needOptions: ["Couples therapy", "Parenting support", "Family communication", "Divorce / separation support", "Blended family support", "Other"],
    seoKeywords: ["family therapist Barcelona", "english speaking family therapy", "couples counselling Barcelona", "terapia familiar inglés"],
  },
  {
    slug: "private-chauffeur",
    name: "Private Chauffeur",
    pluralName: "Private Chauffeurs",
    icon: "🚘",
    shortPitch: "English-speaking private chauffeurs in Barcelona for airport transfers, business trips and personalised tours.",
    needOptions: ["Airport transfer", "Business / corporate travel", "Personalised city tour", "Multi-day / event hire", "Hourly hire", "Other"],
    seoKeywords: ["english speaking chauffeur Barcelona", "private driver Barcelona", "VIP chauffeur Barcelona", "airport transfer english driver Barcelona"],
  },
  {
    slug: "storage-service",
    name: "Storage & Self-Storage",
    pluralName: "Storage & Self-Storage Services",
    icon: "📦",
    shortPitch: "English-speaking self-storage centres and door-to-door storage pickup services in Barcelona, from a single box to a full flat's worth of furniture.",
    needOptions: ["Self-storage unit", "Door-to-door / pickup storage", "Business / commercial storage", "Short-term (moving, renovation)", "Long-term storage", "Other"],
    seoKeywords: ["self storage Barcelona english speaking", "trasteros Barcelona ingles", "door to door storage Barcelona", "storage unit rental Barcelona", "furniture storage Barcelona expat"],
  },
  {
    slug: "house-clearance",
    name: "House & Apartment Clearance",
    pluralName: "House & Apartment Clearance Services",
    icon: "🧹",
    shortPitch: "English-speaking house and apartment clearance in Barcelona, from a single-room clear-out to a full estate or end-of-tenancy clearance.",
    needOptions: ["End-of-tenancy clearance", "Estate / inherited property clearance", "Full house or flat clear-out", "Single room or furniture removal", "Junk / rubbish removal", "Other"],
    seoKeywords: ["house clearance Barcelona english speaking", "apartment clearance Barcelona", "flat clearance Barcelona english", "vaciado de pisos Barcelona ingles", "junk removal Barcelona english", "estate clearance Barcelona"],
  },
  {
    slug: "air-conditioning",
    name: "Air Conditioning Install & Repair",
    pluralName: "Air Conditioning Installers & Repair",
    icon: "❄️",
    shortPitch: "English-speaking air conditioning installers and repair technicians in Barcelona, from a single split unit to full aerothermy systems.",
    needOptions: ["New AC installation", "Repair / not cooling", "Maintenance / refrigerant refill", "Aerothermy / heat pump", "Commercial installation", "Other"],
    seoKeywords: ["air conditioning installation Barcelona english speaking", "AC repair Barcelona english", "aire acondicionado instalacion ingles", "split unit installation Barcelona", "aerothermy Barcelona english"],
  },
  {
    slug: "locksmith",
    name: "Locksmith",
    pluralName: "Locksmiths",
    icon: "🔑",
    shortPitch: "English-speaking emergency locksmiths in Barcelona for lockouts, lock changes and security upgrades, day or night.",
    needOptions: ["Locked out (emergency)", "Lock change or repair", "Security upgrade", "Key duplication", "Safe / commercial lock", "Other"],
    seoKeywords: ["english speaking locksmith Barcelona", "emergency locksmith Barcelona", "cerrajero urgente ingles", "24 hour locksmith Barcelona english", "lockout Barcelona english"],
  },
  {
    slug: "appliance-repair",
    name: "Appliance Repair",
    pluralName: "Appliance Repair Services",
    icon: "🔧",
    shortPitch: "English-speaking appliance repair in Barcelona, from washing machines and boilers to fridges and dishwashers.",
    needOptions: ["Washing machine repair", "Boiler / water heater repair", "Fridge or dishwasher repair", "Installation", "Maintenance contract", "Other"],
    seoKeywords: ["appliance repair Barcelona english speaking", "washing machine repair Barcelona english", "boiler repair Barcelona english", "reparacion electrodomesticos ingles", "white goods repair Barcelona"],
  },
  {
    slug: "pest-control",
    name: "Pest Control",
    pluralName: "Pest Control Services",
    icon: "🐜",
    shortPitch: "English-speaking pest control in Barcelona for cockroaches, bed bugs, rodents and more, with guaranteed treatments.",
    needOptions: ["Cockroaches", "Bed bugs", "Rodents (mice/rats)", "Wasps or ants", "Preventative contract", "Other"],
    seoKeywords: ["pest control Barcelona english speaking", "cockroach treatment Barcelona english", "bed bug removal Barcelona english", "control de plagas ingles", "exterminator Barcelona english"],
  },
  {
    slug: "balcony-terrace-design",
    name: "Balcony & Terrace Design and Furnishing",
    pluralName: "Balcony & Terrace Design and Furnishing Studios",
    icon: "🪴",
    shortPitch: "English-speaking balcony, terrace and rooftop design and furnishing studios in Barcelona, from a small Eixample balcony to a full rooftop reform.",
    needOptions: ["Terrace or rooftop reform", "Balcony furnishing", "Outdoor furniture selection", "Pergola / shade structure", "Full design consultation", "Other"],
    seoKeywords: ["balcony design Barcelona english speaking", "terrace furniture Barcelona english", "rooftop design Barcelona", "outdoor furniture Barcelona english", "terraza diseño ingles"],
  },
  {
    slug: "wedding-planner",
    name: "Wedding Planner",
    pluralName: "Wedding Planners",
    icon: "💍",
    shortPitch: "English-speaking wedding planners in Barcelona for destination weddings, from an intimate elopement to a full multi-day celebration.",
    needOptions: ["Full wedding planning", "Partial / month-of coordination", "Venue sourcing", "Destination wedding (multi-day)", "Elopement / small ceremony", "Other"],
    seoKeywords: ["english speaking wedding planner Barcelona", "destination wedding planner Barcelona", "Barcelona wedding planner international couples", "wedding planner Spain english", "elopement planner Barcelona"],
  },
  {
    slug: "recruiter",
    name: "Recruiter",
    pluralName: "Recruiters",
    icon: "🎯",
    shortPitch: "English-speaking recruiters and headhunters in Barcelona for tech, SaaS and startup hiring, from a single critical role to building out a whole team.",
    needOptions: ["Single role search", "Executive / leadership hire", "Team build-out", "Retained search", "Contingency search", "Other"],
    seoKeywords: ["english speaking recruiter Barcelona", "english speaking headhunter Barcelona", "tech recruiter Barcelona english", "startup headhunter Barcelona", "executive search Barcelona english speaking"],
  },
  {
    slug: "private-chef",
    name: "Private Chef",
    pluralName: "Private Chefs",
    icon: "👨‍🍳",
    shortPitch: "English-speaking private chefs in Barcelona for dinner parties, villa dining and special occasions, cooked and served at your home.",
    needOptions: ["Dinner party", "Special occasion / celebration", "Weekly meal prep", "Corporate event", "Villa / holiday rental dining", "Other"],
    seoKeywords: ["english speaking private chef Barcelona", "private chef Barcelona home dining", "personal chef Barcelona english", "villa private chef Barcelona", "private dining experience Barcelona"],
  },
  {
    slug: "plumber",
    name: "Plumber",
    pluralName: "Plumbers",
    icon: "🔧",
    shortPitch: "English-speaking plumbers in Barcelona for leaks, blocked drains, boilers and bathroom repairs, including emergency call-outs.",
    needOptions: ["Emergency leak or burst pipe", "Blocked drain or toilet", "Boiler or water heater", "Tap, shower or toilet repair", "Bathroom or kitchen installation", "Other"],
    seoKeywords: ["english speaking plumber Barcelona", "emergency plumber Barcelona", "fontanero urgente ingles", "24 hour plumber Barcelona english", "leak repair Barcelona english"],
  },
  {
    slug: "electrician",
    name: "Electrician",
    pluralName: "Electricians",
    icon: "💡",
    shortPitch: "English-speaking electricians in Barcelona for power cuts, faults, rewiring, lighting and safety certificates, including emergencies.",
    needOptions: ["Power cut or tripping fuse box", "Faulty socket or switch", "Lighting installation", "Rewiring or upgrade", "Electrical safety certificate", "Other"],
    seoKeywords: ["english speaking electrician Barcelona", "emergency electrician Barcelona", "electricista urgente ingles", "24 hour electrician Barcelona english", "power cut Barcelona english"],
  },
  {
    slug: "movers",
    name: "Removals & International Movers",
    pluralName: "Removals & International Movers",
    icon: "🚚",
    shortPitch: "English-speaking removals companies and international movers in Barcelona, for moves within the city, to Barcelona from abroad, or out of Spain.",
    needOptions: ["Move within Barcelona", "International move to Barcelona", "International move out of Spain", "Packing and unpacking", "Furniture-only or small move", "Other"],
    seoKeywords: ["english speaking movers Barcelona", "removals Barcelona english", "international movers Barcelona", "mudanzas internacionales ingles", "moving to Barcelona removals company"],
  },
  {
    slug: "psychiatrist",
    name: "Psychiatrist",
    pluralName: "Psychiatrists",
    icon: "🧠",
    shortPitch: "English-speaking psychiatrists in Barcelona for ADHD assessment, anxiety, depression and medication management.",
    needOptions: ["ADHD assessment", "Medication review or prescription", "Anxiety or depression", "Bipolar, OCD or other diagnosis", "Second opinion", "Other"],
    seoKeywords: ["english speaking psychiatrist Barcelona", "ADHD assessment Barcelona english", "psiquiatra ingles Barcelona", "psychiatrist for expats Barcelona", "private psychiatrist Barcelona"],
  },
];

// Use this everywhere a category is listed for a visitor to pick from (nav,
// grids, the lead form, the sitemap). `categories` and `getCategory` stay
// unfiltered so already-hidden categories' data (e.g. existing verified
// listings) keeps working the moment `hidden` is flipped back off.
export const visibleCategories: Category[] = categories.filter((c) => !c.hidden);

export function getArea(slug: string): Area | undefined {
  return areas.find((a) => a.slug === slug);
}

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
