import type { Professional } from "./types";

// ---------------------------------------------------------------------------
// DIRECTORY LISTINGS (real businesses, NOT paying partners)
// ---------------------------------------------------------------------------
// Sourced from public web search results, August 2026. These are genuine,
// findable English-speaking practices, nothing here is invented. But:
//
//  - None of these businesses have agreed to be featured or to receive
//    leads from this site. `isPartner` is false for all of them, they get
//    no special placement, just an honest directory entry.
//  - Contact details are deliberately NOT included (no phone/WhatsApp
//    number). Search-result summaries can misattribute phone numbers and
//    addresses, and publishing a wrong number against a real clinic's name
//    is worse than publishing nothing. `bookingUrl` links straight to the
//    business's own site (taken directly from the search result URL, not
//    summarized) so visitors, and you, can verify everything there.
//  - `addressArea` is kept at neighbourhood level and only used where the
//    source explicitly ties the business to that district.
//  - Spot-check every entry (still operating, still English-speaking,
//    still at that location) before this ever reaches a partner conversation
//    or a real user, and swap in a real paying partner via `isPartner: true`
//    the moment you sign one for that area + category.
// ---------------------------------------------------------------------------
export const professionals: Professional[] = [
  {
    id: "poblenou-doctor-english-doctor-barcelona",
    name: "English Doctor Barcelona",
    categorySlug: "doctor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://englishdoctorbarcelona.com",
  },
  {
    id: "les-corts-doctor-googol",
    name: "Googol Medical Centre",
    categorySlug: "doctor",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Psychiatry"],
    languages: ["English", "Spanish"],
    addressArea: "Les Corts",
    bookingUrl: "http://www.googolmedicalcentre.com/General_practice.html",
  },
  {
    id: "sarria-dermatologist-turo-park",
    name: "Turó Park Medical Centre",
    categorySlug: "dermatologist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & cosmetic dermatology", "Skin checks"],
    languages: ["English", "Spanish", "and other languages"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/dermatology/",
  },
  {
    id: "les-corts-dentist-campi",
    name: "Campi Dental Clinic",
    categorySlug: "dentist",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & family dentistry"],
    languages: ["English", "Spanish", "Catalan", "and other languages"],
    addressArea: "Les Corts / Sarrià border",
    bookingUrl: "https://www.clinicadentalcampi.com/en/",
  },
  {
    id: "poblenou-chiropractor-puravida",
    name: "Puravida Chiropractic",
    categorySlug: "chiropractor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Spinal adjustment", "General chiropractic care"],
    languages: ["English", "Spanish", "Catalan", "Portuguese", "French"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://puravidaquiropractica.com/en/",
  },
  {
    id: "eixample-chiropractor-quiropractica-eixample",
    name: "Quiropráctica Eixample",
    categorySlug: "chiropractor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Chiropractic care", "Posture correction"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://www.quiropracticaeixample.com/en/",
  },
  {
    id: "sarria-chiropractor-sarria-quiropractica",
    name: "Sarrià Quiropráctica",
    categorySlug: "chiropractor",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Family chiropractic care"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://sarriaquiropractica.es/en/",
  },
  {
    id: "eixample-acupuncturist-tania-spearman",
    name: "Tania Spearman Acupuncture",
    categorySlug: "acupuncturist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture", "Traditional Chinese Medicine"],
    languages: ["English", "Spanish", "German"],
    addressArea: "Eixample",
    bookingUrl: "https://taniaspearman.com",
  },
  {
    id: "sarria-acupuncturist-acubarcelona",
    name: "AcuBarcelona",
    categorySlug: "acupuncturist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture", "Traditional Chinese Medicine"],
    languages: ["English"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://acubarcelona.com",
  },
  {
    id: "sarria-physiotherapist-physio-barcelona",
    name: "Physiotherapy Barcelona",
    categorySlug: "physiotherapist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General physiotherapy", "Sports injuries", "Rehabilitation"],
    languages: ["English", "Dutch", "German", "Spanish"],
    addressArea: "Sant Gervasi",
    bookingUrl: "https://www.physiotherapybarcelona.com/en",
  },
  {
    id: "eixample-physiotherapist-dpn",
    name: "DPN Fisioterapia",
    categorySlug: "physiotherapist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Physiotherapy", "Rehabilitation"],
    languages: ["English", "Spanish", "Portuguese"],
    addressArea: "Eixample",
    bookingUrl: "https://dpnfisioterapia.com/en/home/",
  },
  {
    id: "eixample-lawyer-myspainvisa",
    name: "MySpain Visa",
    categorySlug: "lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Immigration law", "Real estate law"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://myspainvisa.com/immigration-lawyers-barcelona/",
  },
  {
    id: "eixample-psychologist-therapy-in-barcelona",
    name: "Therapy in Barcelona",
    categorySlug: "psychologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Individual therapy", "Group therapy", "Expat community support"],
    languages: ["English", "and other languages"],
    addressArea: "Eixample",
    bookingUrl: "https://www.therapyinbarcelona.com/",
  },
  {
    id: "sarria-fertility-turo-park",
    name: "Turó Park Clinics: Fertility & AHR",
    categorySlug: "fertility-clinic",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Assisted human reproduction"],
    languages: ["English", "Spanish", "and other languages"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/fertility-and-ahr-barcelona/",
  },
  {
    id: "sarria-plastic-surgeon-barcelona-facial-plastics",
    name: "Barcelona Facial Plastics",
    categorySlug: "plastic-surgeon",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Facial plastic surgery", "Cosmetic procedures"],
    languages: ["English", "Spanish"],
    addressArea: "Via Augusta, Sarrià-Sant Gervasi",
    bookingUrl: "https://barcelonafacialplastics.com/",
  },
  {
    id: "sarria-lasik-teknon",
    name: "Centro Médico Teknon: Refractive Surgery Unit",
    categorySlug: "lasik",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["LASIK", "Refractive surgery", "General ophthalmology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://www.teknon.es/en/specialities/fernandez-agrafojo-dora/refractive-surgery",
  },
  {
    id: "poblenou-vet-clinica-veterinaria-poblenou",
    name: "Clínica Veterinària Poblenou",
    categorySlug: "veterinarian",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Check-ups", "Vaccinations"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://guia.barcelona.cat/en/detall/clinica-veterinaria-poblenou_75990015511.html",
  },
  {
    id: "eixample-vet-balmesvet",
    name: "Balmesvet Veterinary Hospital",
    categorySlug: "veterinarian",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["24h emergency", "Surgery", "Hospitalization"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://balmesvet.com/en/",
  },
  {
    id: "sarria-nutritionist-turo-park",
    name: "Turó Park Clinics: Nutritionist",
    categorySlug: "nutritionist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Personalized nutrition programs", "Integrative nutrition"],
    languages: ["English", "Spanish", "French", "Catalan"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/nutritionist-barcelona/",
  },
  {
    id: "eixample-naturopath-anne-laure-naudin",
    name: "Anne-Laure Naudin: Naturopath",
    categorySlug: "naturopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Nutrition", "Phytotherapy", "Stress management"],
    languages: ["English", "French", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://www.annelaurenaudin.com/",
  },
  {
    id: "eixample-tax-advisor-manor-tax",
    name: "Manor Tax Services SLP",
    categorySlug: "tax-advisor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["International taxation", "Tax management for expats & digital nomads"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://barcelona.cool/en/categorias/asesorias-fiscales-internacionales/manor-tax-barcelona",
  },
  {
    id: "poblenou-property-advisor-xela",
    name: "Xela Properties",
    categorySlug: "property-advisor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property sales", "Poblenou & 22@ specialists"],
    languages: ["English", "Spanish", "Catalan", "French"],
    addressArea: "Poblenou, 22@ district",
    bookingUrl: "https://xelaprop.com/en/team/",
  },
  {
    id: "poblenou-property-advisor-immobarcelo",
    name: "ImmoBarceló",
    categorySlug: "property-advisor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Buying, selling & renting property"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou",
    bookingUrl: "https://immobarcelo.es/en/",
  },
  {
    id: "eixample-dentist-el-cedro",
    name: "El Cedro Barcelona",
    categorySlug: "dentist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & family dentistry"],
    languages: ["English", "Spanish", "French"],
    addressArea: "Eixample",
    bookingUrl: "https://www.elcedrobarcelona.com/en/english-speaking-dental-clinic/",
  },
  {
    id: "sarria-dentist-raslan",
    name: "Clínica Dental Raslan",
    categorySlug: "dentist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish", "Catalan"],
    addressArea: "Sarrià-Sant Gervasi, near La Bonanova",
    bookingUrl: "https://clinicaraslan.com/en/work-team/",
  },
  {
    id: "eixample-doctor-traveldoctores",
    name: "TravelDoctores (video consultations)",
    categorySlug: "doctor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Video GP consultations"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample (online video consultations)",
    bookingUrl: "https://traveldoctores.com/doctor-in-barcelona-english-speaking/",
  },
  {
    id: "poblenou-psychologist-therapy-in-barcelona-el-clot",
    name: "Therapy in Barcelona: El Clot",
    categorySlug: "psychologist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Individual therapy", "Serves Poblenou & Sant Martí"],
    languages: ["English", "and other languages"],
    addressArea: "El Clot, near Poblenou",
    bookingUrl: "https://www.therapyinbarcelona.com/el-clot/",
  },
  {
    id: "sarria-psychologist-psicare",
    name: "PsIcare Health",
    categorySlug: "psychologist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Mental health clinic", "American-trained psychologists"],
    languages: ["English"],
    addressArea: "Sarrià-Sant Gervasi",
  },
  {
    id: "poblenou-dermatologist-english-doctor-barcelona",
    name: "English Doctor Barcelona",
    categorySlug: "dermatologist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Dermatology consultations", "Diagnostics & specialist referrals"],
    languages: ["English", "Spanish", "French", "Hindi", "Arabic"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://englishdoctorbarcelona.com",
  },
  {
    id: "eixample-dermatologist-saban",
    name: "Saban Dermatología",
    categorySlug: "dermatologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Clinical, surgical & cosmetic dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
  },
  {
    id: "eixample-fertility-reproclinic",
    name: "Reproclinic",
    categorySlug: "fertility-clinic",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Assisted reproduction"],
    languages: ["English", "Spanish", "Catalan", "French", "Italian", "German", "Dutch", "Portuguese"],
    addressArea: "Left Eixample, near Sant Antoni",
    bookingUrl: "https://www.fertilityclinicsabroad.com/clinics/reproclinic/",
  },
  {
    id: "les-corts-physiotherapist-mes",
    name: "MES Fisioterapia",
    categorySlug: "physiotherapist",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Physiotherapy", "Sports physiotherapy", "Osteopathy"],
    languages: ["English", "Spanish"],
    addressArea: "Les Corts",
    bookingUrl: "https://www.mesfisioterapia.com/home_en",
  },
  {
    id: "sarria-obgyn-turo-park",
    name: "Turó Park Clinics: Dr. Berta Esteban",
    categorySlug: "obgyn-midwife",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Gynaecology", "Gynaecological surgery"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/english-speaking-gynecologist-barcelona/",
  },
  {
    id: "sarria-obgyn-onbargi-teknon",
    name: "Dr. Leila Onbargi: Centro Médico Teknon",
    categorySlug: "obgyn-midwife",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Obstetrics", "Gynaecology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://www.barcelona-metropolitan.com/locations/centro-medico-teknon-Onbargi-gynecologist/",
  },
  {
    id: "poblenou-midwife-tribu-house",
    name: "Tribu House: Doula & Birth Support",
    categorySlug: "obgyn-midwife",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Doula support", "Birth & postpartum accompaniment"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://tribuhouse.com/en/services/acompanamiento-doula/",
  },
  {
    id: "sarria-pediatrician-turo-park",
    name: "Turó Park Medical Clinic",
    categorySlug: "pediatrician",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General pediatrics", "Diagnostics"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://turoparkmedical.com/english-speaking-pediatrician/",
  },
  {
    id: "eixample-pediatrician-arcc",
    name: "Centro Pediátrico ARCC Barcelona",
    categorySlug: "pediatrician",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General pediatrics", "Childhood allergies", "Pediatric traumatology"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
  },
  {
    id: "eixample-osteopath-malecot",
    name: "Malécot Osteopathy",
    categorySlug: "osteopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Adults", "Babies", "Pregnancy osteopathy"],
    languages: ["English", "French", "Spanish"],
    addressArea: "Eixample, near Plaça Universitat",
    bookingUrl: "https://malecotosteopatiabarcelona.com/en/",
  },
  {
    id: "gracia-osteopath-david-arbona",
    name: "David Arbona Osteopathy",
    categorySlug: "osteopath",
    areaSlug: "gracia",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Osteopathy"],
    languages: ["English", "Spanish"],
    addressArea: "Gràcia (also sees patients in Eixample)",
    bookingUrl: "https://davidarbona.com/en/david-arbona-osteopathy-in-barcelona/",
  },
  {
    id: "eixample-business-lawyer-forcam",
    name: "Forcam Lawyers",
    categorySlug: "business-lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Company formation", "Shareholder disputes", "Corporate maintenance"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample, near Plaça Francesc Macià",
    bookingUrl: "https://www.forcamabogados.com/en/lawyers-barcelona",
  },
  {
    id: "eixample-orthodontist-turo-park",
    name: "Turó Park Clinics: Dr. Madeleine Smit",
    categorySlug: "orthodontist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign", "Lingual orthodontics", "Invisible braces"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer Francesc Pérez Cabrero, Eixample",
    bookingUrl: "https://turoparkmedical.com/dental-clinic-barcelona/orthodontist/",
  },
  {
    id: "sarria-orthodontist-dental-spa",
    name: "Dental Spa Clinics",
    categorySlug: "orthodontist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign", "SureSmile", "Lingual orthodontics"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Balmes, Sarrià-Sant Gervasi",
    bookingUrl: "https://dentalspaclinics.com/en/",
  },
  {
    id: "poblenou-orthodontist-maba",
    name: "MABA Odontología Avanzada",
    categorySlug: "orthodontist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign clear aligners", "Orthodontic bite correction"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://www.mabadental.es/we-speak-english",
  },
  {
    id: "sarria-podiatrist-turo-park",
    name: "Turó Park Clinics: Podiatry",
    categorySlug: "podiatrist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Biomechanics", "Ingrown toenail surgery", "Gait analysis"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/podiatrist-in-barcelona/",
  },
  {
    id: "sarria-eye-care-turo-park",
    name: "Turó Park Clinics: Ophthalmology",
    categorySlug: "eye-care",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Eye exams", "General ophthalmology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/your-ophthalmologist-in-barcelona/",
  },
  {
    id: "sarria-insurance-inov-expat",
    name: "INOV Expat",
    categorySlug: "insurance-broker",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Health insurance", "Home insurance", "Car insurance"],
    languages: ["English", "French", "Spanish", "Portuguese", "Russian"],
    addressArea: "Via Augusta, Sant Gervasi",
    bookingUrl: "https://www.inovexpat.com/en/inov-expat-en/",
  },
  {
    id: "sarria-wealth-manager-w1m",
    name: "W1M",
    categorySlug: "wealth-manager",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Expat wealth management", "Investment planning"],
    languages: ["English", "Spanish"],
    addressArea: "Ronda General Mitre, Sarrià-Sant Gervasi",
    bookingUrl: "https://www.w1m.com/individuals-families/expats-europe/",
  },
  {
    id: "eixample-notary-jla",
    name: "JLA Notarios",
    categorySlug: "notary",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property purchase signings", "Document certification"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    bookingUrl: "https://www.jlanotarios.com/en_GB/",
  },
  {
    id: "eixample-notary-benavides",
    name: "Notaría Jesús Benavides",
    categorySlug: "notary",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property purchase signings", "Power of attorney"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    bookingUrl: "https://en.jesusbenavides.es/",
  },
  // -------------------------------------------------------------------
  // Google Maps sweep (live search via Claude in Chrome, Aug 2026).
  // Standard: included only where the visible Maps review snippet or the
  // business's own name explicitly confirms English service, cross-checked
  // against the address for area. No bookingUrl captured for these yet
  // (not individually visited) - card renders without a "Visit website"
  // button until enriched with a confirmed direct URL.
  // -------------------------------------------------------------------
  {
    id: "eixample-notary-blas-lluna",
    name: "Notaria de Blas & Lluna",
    categorySlug: "notary",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property purchase signings", "Document certification"],
    languages: ["English", "Spanish"],
    addressArea: "Passeig de Gràcia, Eixample",
    ratingLabel: "4.8 (188 reviews) on Google Maps",
  },
  {
    id: "eixample-dentist-opal",
    name: "Clínica Dental Opal",
    categorySlug: "dentist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish"],
    addressArea: "Passeig de Sant Joan, Eixample",
    ratingLabel: "4.9 (99 reviews) on Google Maps",
  },
  {
    id: "eixample-dentist-the-practice",
    name: "The Practice Barcelona",
    categorySlug: "dentist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & family dentistry"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer del Comte d'Urgell, Eixample",
    ratingLabel: "4.9 (149 reviews) on Google Maps",
  },
  {
    id: "eixample-lawyer-advocate-abroad",
    name: "Advocate Abroad",
    categorySlug: "lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["International & property law"],
    languages: ["English", "Spanish"],
    addressArea: "Gran Via de les Corts Catalanes, Eixample",
    ratingLabel: "4.7 (253 reviews) on Google Maps",
  },
  {
    id: "eixample-lawyer-klevvera",
    name: "Klev&Vera International Law Firm",
    categorySlug: "lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["International law"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de València, Eixample",
    ratingLabel: "4.8 (202 reviews) on Google Maps",
  },
  {
    id: "eixample-dermatologist-de-felip",
    name: "Clínica Dermatològica De Felip",
    categorySlug: "dermatologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Muntaner, Eixample",
    ratingLabel: "4.6 (1,898 reviews) on Google Maps",
  },
  {
    id: "eixample-dermatologist-inederm",
    name: "Inederm, Institut Eixample de Dermatologia",
    categorySlug: "dermatologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Casp, Eixample",
    ratingLabel: "4.6 (390 reviews) on Google Maps",
  },
  {
    id: "eixample-doctor-american-english",
    name: "American and English Speaking Doctor Barcelona",
    categorySlug: "doctor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Home visits", "Online consultations"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Aragó, Eixample",
    ratingLabel: "4.9 (132 reviews) on Google Maps",
  },
  {
    id: "eixample-physiotherapist-perales",
    name: "Sports Physiotherapy by Perales",
    categorySlug: "physiotherapist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Sports physiotherapy"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Lepant, Eixample",
    ratingLabel: "5.0 (40 reviews) on Google Maps",
  },
  {
    id: "eixample-physiotherapist-gallofre",
    name: "Enric Gallofré Physiotherapy and Osteopathy Clinic",
    categorySlug: "physiotherapist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Physiotherapy", "Osteopathy"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Ausiàs Marc, Eixample",
    ratingLabel: "4.9 (501 reviews) on Google Maps",
  },
  {
    id: "eixample-psychologist-monika-varela",
    name: "Monika Varela",
    categorySlug: "psychologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Meditation & mindfulness coaching", "Individual therapy"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Enric Granados, Eixample",
    ratingLabel: "5.0 (24 reviews) on Google Maps",
  },
  {
    id: "eixample-psychologist-therapy-counseling",
    name: "Therapy and Counseling in Barcelona",
    categorySlug: "psychologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Individual therapy", "Counseling"],
    languages: ["English", "Russian", "Spanish", "Catalan"],
    addressArea: "Passeig de Sant Joan, Eixample",
    ratingLabel: "4.4 (11 reviews) on Google Maps",
  },
  {
    id: "eixample-fertility-barcelona-ivf",
    name: "Barcelona IVF",
    categorySlug: "fertility-clinic",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Fertility treatment"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de les Escoles Pies, Eixample",
    ratingLabel: "4.5 (564 reviews) on Google Maps",
  },
  {
    id: "eixample-fertility-eugin",
    name: "Clínica EUGIN Barcelona",
    categorySlug: "fertility-clinic",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Egg donation", "Fertility treatment"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Balmes, Eixample",
    ratingLabel: "4.2 (633 reviews) on Google Maps",
  },
  {
    id: "eixample-chiropractor-puravida",
    name: "Puravida Quiropráctica Barcelona - Eixample",
    categorySlug: "chiropractor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Spinal adjustment", "General chiropractic care"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer del Bruc, Eixample",
    ratingLabel: "4.9 (633 reviews) on Google Maps",
  },
  {
    id: "eixample-chiropractor-illuminnate",
    name: "illumINNATE Chiropractic Studio",
    categorySlug: "chiropractor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Chiropractic care"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Roger de Llúria, Eixample",
    ratingLabel: "4.7 (89 reviews) on Google Maps",
  },
  {
    id: "eixample-tax-advisor-htj",
    name: "HTJ.Tax in Spain",
    categorySlug: "tax-advisor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["US tax services", "Cross-border tax"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de la Diputació, Eixample",
    ratingLabel: "5.0 (288 reviews) on Google Maps",
  },
  {
    id: "eixample-tax-advisor-jdv-expatax",
    name: "JDV EXPATAX",
    categorySlug: "tax-advisor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Expat tax advice"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    ratingLabel: "4.9 (19 reviews) on Google Maps",
  },
  {
    id: "eixample-acupuncturist-balanced-living",
    name: "Balanced Living",
    categorySlug: "acupuncturist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Aribau, Eixample",
    ratingLabel: "4.7 (229 reviews) on Google Maps",
  },
  {
    id: "eixample-acupuncturist-centre-holistic",
    name: "Centre Holístic",
    categorySlug: "acupuncturist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture", "Holistic therapies"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de los Castillejos, Eixample",
    ratingLabel: "4.9 (36 reviews) on Google Maps",
  },
  {
    id: "eixample-plastic-surgeon-imagn",
    name: "Imagn Institute — Dr. Ahmad Saad",
    categorySlug: "plastic-surgeon",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Plastic surgery", "American Board of Plastic Surgery diplomate"],
    languages: ["English", "Spanish"],
    addressArea: "Rambla de Catalunya, Eixample",
    ratingLabel: "4.9 (114 reviews) on Google Maps",
  },
  {
    id: "sarria-plastic-surgeon-nanhekhan",
    name: "Dr. Lloyd Nanhekhan — Turó Park Aesthetic Clinic",
    categorySlug: "plastic-surgeon",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Plastic surgery"],
    languages: ["English", "French", "Dutch", "German", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    ratingLabel: "4.7 (13 reviews) on Google Maps",
  },
  {
    id: "sarria-lasik-visioncore",
    name: "VISIONCORE Clínica Oftalmológica",
    categorySlug: "lasik",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General ophthalmology", "Eye emergencies"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer dels Madrazo, Sarrià-Sant Gervasi",
    ratingLabel: "5.0 (585 reviews) on Google Maps",
  },
  {
    id: "eixample-nutritionist-narella-muzzio",
    name: "Narella Muzzio",
    categorySlug: "nutritionist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Nutrition planning", "Vegan diets"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de la Diputació, Eixample",
    ratingLabel: "4.9 (56 reviews) on Google Maps",
  },
  {
    id: "eixample-nutritionist-cabanas",
    name: "Cabanas Nutrition",
    categorySlug: "nutritionist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Nutrition planning"],
    languages: ["English", "Spanish", "Catalan"],
    addressArea: "Carrer de Còrsega, near Sagrada Família, Eixample",
    ratingLabel: "5.0 (48 reviews) on Google Maps",
  },
  {
    id: "eixample-osteopath-massage-therapist",
    name: "Massage Therapist and Osteopath in Barcelona",
    categorySlug: "osteopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Osteopathy", "Massage therapy"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Pau Claris, Eixample",
    ratingLabel: "5.0 (18 reviews) on Google Maps",
  },
  {
    id: "eixample-osteopath-gallofre",
    name: "Enric Gallofré Physiotherapy and Osteopathy Clinic",
    categorySlug: "osteopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Osteopathy", "Physiotherapy"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Ausiàs Marc, Eixample",
    ratingLabel: "4.9 (501 reviews) on Google Maps",
  },
  {
    id: "poblenou-doctor-medvisit",
    name: "English Speaking Doctors - MedVisit",
    categorySlug: "doctor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Home visits", "Pediatric care"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Bilbao, Poblenou",
    ratingLabel: "4.8 (688 reviews) on Google Maps",
  },
  {
    id: "eixample-business-lawyer-legal70",
    name: "Legal 70 Group",
    categorySlug: "business-lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Corporate & business law"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Roger de Llúria, Eixample",
    ratingLabel: "5.0 (50 reviews) on Google Maps",
  },
  {
    id: "eixample-business-lawyer-lexidy",
    name: "Lexidy Law Boutique",
    categorySlug: "business-lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Company formation", "Corporate law"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    ratingLabel: "4.5 (364 reviews) on Google Maps",
  },
  {
    id: "eixample-business-lawyer-intlaw",
    name: "Abogados - Intlaw",
    categorySlug: "business-lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Startup & business law", "Company formation"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer d'Aribau, Eixample",
    ratingLabel: "4.6 (53 reviews) on Google Maps",
  },
  {
    id: "eixample-insurance-broker-niebcn",
    name: "NIEBCN",
    categorySlug: "insurance-broker",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Health insurance", "General insurance brokerage"],
    languages: ["English", "Spanish", "German"],
    addressArea: "Rambla de Catalunya, Eixample",
    ratingLabel: "5.0 (101 reviews) on Google Maps",
  },
  {
    id: "eixample-insurance-broker-cogesa",
    name: "Cogesa Expats",
    categorySlug: "insurance-broker",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Expat insurance brokerage"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de la Diputació, Eixample",
    ratingLabel: "5.0 (61 reviews) on Google Maps",
  },
  {
    id: "eixample-autonomo-accountant-spain-france",
    name: "Spain and France Accountants",
    categorySlug: "autonomo-accountant",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Autónomo tax filings", "Cross-border accounting"],
    languages: ["English", "Spanish", "French"],
    addressArea: "Carrer de Padilla, Eixample",
    ratingLabel: "4.8 (86 reviews) on Google Maps",
  },
  {
    id: "eixample-autonomo-accountant-global-mind",
    name: "Global Mind Advisors",
    categorySlug: "autonomo-accountant",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Freelancer & autónomo accounting", "Financial consulting"],
    languages: ["English", "Spanish"],
    addressArea: "Plaça d'Urquinaona, Eixample",
    ratingLabel: "5.0 (54 reviews) on Google Maps",
  },
  {
    id: "eixample-autonomo-accountant-grupo-gestor",
    name: "Grupo Gestor BCN",
    categorySlug: "autonomo-accountant",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Autónomo & freelancer tax filings"],
    languages: ["English", "Spanish"],
    addressArea: "Rambla de Catalunya, Eixample",
    ratingLabel: "4.5 (176 reviews) on Google Maps",
  },
  {
    id: "poblenou-dentist-alejandra-higueras",
    name: "Alejandra Higueras Clínica Dental",
    categorySlug: "dentist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Pujades, Poblenou",
    ratingLabel: "4.9 (944 reviews) on Google Maps",
  },
  {
    id: "poblenou-dentist-instituts-odontologics",
    name: "Instituts Odontològics - Clínica Dental Barcelona Poblenou",
    categorySlug: "dentist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Ramon Turró, Poblenou",
    ratingLabel: "4.4 (361 reviews) on Google Maps",
  },
  {
    id: "poblenou-dentist-roig-espona",
    name: "Clínica Dental Roig Espona",
    categorySlug: "dentist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Bilbao, Poblenou",
    ratingLabel: "4.8 (65 reviews) on Google Maps",
  },
];

// Used only on the internal /partners sales-preview page to show a prospective
// partner what their featured card will look like. Never rendered on public
// area/category pages.
export const exampleProfessional: Professional = {
  id: "example-preview",
  name: "Your Clinic Name",
  categorySlug: "dentist",
  areaSlug: "poblenou",
  isPartner: true,
  isPlaceholder: true,
  specialties: ["Implants", "Invisalign", "Cosmetic dentistry"],
  languages: ["English", "Spanish", "Catalan"],
  addressArea: "Poblenou, Barcelona",
  phoneDisplay: "+34 9XX XXX XXX",
  bookingUrl: "#",
  ratingLabel: "Recommended partner",
};

export function getProfessionals(areaSlug: string, categorySlug: string): Professional[] {
  return professionals
    .filter((p) => p.areaSlug === areaSlug && p.categorySlug === categorySlug)
    .sort((a, b) => Number(b.isPartner) - Number(a.isPartner));
}
