import type { Professional } from "./types";

// ---------------------------------------------------------------------------
// DIRECTORY LISTINGS (real businesses, NOT paying partners)
// ---------------------------------------------------------------------------
// Sourced from public web search results, August 2026. These are genuine,
// findable English-speaking practices, nothing here is invented. But:
//
//  - None of these businesses have agreed to be featured or to receive
//    leads from this site. `isPartner` is false for all of them, they get
//    no special placement, just an honest directory entry.
//  - Contact details are deliberately NOT included (no phone/WhatsApp
//    number). Search-result summaries can misattribute phone numbers and
//    addresses, and publishing a wrong number against a real clinic's name
//    is worse than publishing nothing. `bookingUrl` links straight to the
//    business's own site (taken directly from the search result URL, not
//    summarized) so visitors, and you, can verify everything there.
//  - `addressArea` is kept at neighbourhood level and only used where the
//    source explicitly ties the business to that district.
//  - Spot-check every entry (still operating, still English-speaking,
//    still at that location) before this ever reaches a partner conversation
//    or a real user, and swap in a real paying partner via `isPartner: true`
//    the moment you sign one for that area + category.
// ---------------------------------------------------------------------------
export const professionals: Professional[] = [
  {
    id: "poblenou-doctor-english-doctor-barcelona",
    name: "English Doctor Barcelona",
    categorySlug: "doctor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://englishdoctorbarcelona.com",
  },
  {
    id: "les-corts-doctor-googol",
    name: "Googol Medical Centre",
    categorySlug: "doctor",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General practice", "Psychiatry"],
    languages: ["English", "Spanish"],
    addressArea: "Les Corts",
    bookingUrl: "http://www.googolmedicalcentre.com/General_practice.html",
  },
  {
    id: "sarria-dermatologist-turo-park",
    name: "Turó Park Medical Centre",
    categorySlug: "dermatologist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & cosmetic dermatology", "Skin checks"],
    languages: ["English", "Spanish", "and other languages"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/dermatology/",
  },
  {
    id: "les-corts-dentist-campi",
    name: "Campi Dental Clinic",
    categorySlug: "dentist",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & family dentistry"],
    languages: ["English", "Spanish", "Catalan", "and other languages"],
    addressArea: "Les Corts / Sarrià border",
    bookingUrl: "https://www.clinicadentalcampi.com/en/",
  },
  {
    id: "poblenou-chiropractor-puravida",
    name: "Puravida Chiropractic",
    categorySlug: "chiropractor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Spinal adjustment", "General chiropractic care"],
    languages: ["English", "Spanish", "Catalan", "Portuguese", "French"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://puravidaquiropractica.com/en/",
  },
  {
    id: "eixample-chiropractor-quiropractica-eixample",
    name: "Quiropráctica Eixample",
    categorySlug: "chiropractor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Chiropractic care", "Posture correction"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://www.quiropracticaeixample.com/en/",
  },
  {
    id: "sarria-chiropractor-sarria-quiropractica",
    name: "Sarrià Quiropráctica",
    categorySlug: "chiropractor",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Family chiropractic care"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://sarriaquiropractica.es/en/",
  },
  {
    id: "eixample-acupuncturist-tania-spearman",
    name: "Tania Spearman Acupuncture",
    categorySlug: "acupuncturist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture", "Traditional Chinese Medicine"],
    languages: ["English", "Spanish", "German"],
    addressArea: "Eixample",
    bookingUrl: "https://taniaspearman.com",
  },
  {
    id: "sarria-acupuncturist-acubarcelona",
    name: "AcuBarcelona",
    categorySlug: "acupuncturist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Acupuncture", "Traditional Chinese Medicine"],
    languages: ["English"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://acubarcelona.com",
  },
  {
    id: "sarria-physiotherapist-physio-barcelona",
    name: "Physiotherapy Barcelona",
    categorySlug: "physiotherapist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General physiotherapy", "Sports injuries", "Rehabilitation"],
    languages: ["English", "Dutch", "German", "Spanish"],
    addressArea: "Sant Gervasi",
    bookingUrl: "https://www.physiotherapybarcelona.com/en",
  },
  {
    id: "eixample-physiotherapist-dpn",
    name: "DPN Fisioterapia",
    categorySlug: "physiotherapist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Physiotherapy", "Rehabilitation"],
    languages: ["English", "Spanish", "Portuguese"],
    addressArea: "Eixample",
    bookingUrl: "https://dpnfisioterapia.com/en/home/",
  },
  {
    id: "eixample-lawyer-myspainvisa",
    name: "MySpain Visa",
    categorySlug: "lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Immigration law", "Real estate law"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://myspainvisa.com/immigration-lawyers-barcelona/",
  },
  {
    id: "eixample-psychologist-therapy-in-barcelona",
    name: "Therapy in Barcelona",
    categorySlug: "psychologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Individual therapy", "Group therapy", "Expat community support"],
    languages: ["English", "and other languages"],
    addressArea: "Eixample",
    bookingUrl: "https://www.therapyinbarcelona.com/",
  },
  {
    id: "sarria-fertility-turo-park",
    name: "Turó Park Clinics: Fertility & AHR",
    categorySlug: "fertility-clinic",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Assisted human reproduction"],
    languages: ["English", "Spanish", "and other languages"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/fertility-and-ahr-barcelona/",
  },
  {
    id: "sarria-plastic-surgeon-barcelona-facial-plastics",
    name: "Barcelona Facial Plastics",
    categorySlug: "plastic-surgeon",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Facial plastic surgery", "Cosmetic procedures"],
    languages: ["English", "Spanish"],
    addressArea: "Via Augusta, Sarrià-Sant Gervasi",
    bookingUrl: "https://barcelonafacialplastics.com/",
  },
  {
    id: "sarria-lasik-teknon",
    name: "Centro Médico Teknon: Refractive Surgery Unit",
    categorySlug: "lasik",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["LASIK", "Refractive surgery", "General ophthalmology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://www.teknon.es/en/specialities/fernandez-agrafojo-dora/refractive-surgery",
  },
  {
    id: "poblenou-vet-clinica-veterinaria-poblenou",
    name: "Clínica Veterinària Poblenou",
    categorySlug: "veterinarian",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Check-ups", "Vaccinations"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://guia.barcelona.cat/en/detall/clinica-veterinaria-poblenou_75990015511.html",
  },
  {
    id: "eixample-vet-balmesvet",
    name: "Balmesvet Veterinary Hospital",
    categorySlug: "veterinarian",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["24h emergency", "Surgery", "Hospitalization"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://balmesvet.com/en/",
  },
  {
    id: "sarria-nutritionist-turo-park",
    name: "Turó Park Clinics: Nutritionist",
    categorySlug: "nutritionist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Personalized nutrition programs", "Integrative nutrition"],
    languages: ["English", "Spanish", "French", "Catalan"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/nutritionist-barcelona/",
  },
  {
    id: "eixample-naturopath-anne-laure-naudin",
    name: "Anne-Laure Naudin: Naturopath",
    categorySlug: "naturopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Nutrition", "Phytotherapy", "Stress management"],
    languages: ["English", "French", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://www.annelaurenaudin.com/",
  },
  {
    id: "eixample-tax-advisor-manor-tax",
    name: "Manor Tax Services SLP",
    categorySlug: "tax-advisor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["International taxation", "Tax management for expats & digital nomads"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
    bookingUrl: "https://barcelona.cool/en/categorias/asesorias-fiscales-internacionales/manor-tax-barcelona",
  },
  {
    id: "poblenou-property-advisor-xela",
    name: "Xela Properties",
    categorySlug: "property-advisor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property sales", "Poblenou & 22@ specialists"],
    languages: ["English", "Spanish", "Catalan", "French"],
    addressArea: "Poblenou, 22@ district",
    bookingUrl: "https://xelaprop.com/en/team/",
  },
  {
    id: "poblenou-property-advisor-immobarcelo",
    name: "ImmoBarceló",
    categorySlug: "property-advisor",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Buying, selling & renting property"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou",
    bookingUrl: "https://immobarcelo.es/en/",
  },
  {
    id: "eixample-dentist-el-cedro",
    name: "El Cedro Barcelona",
    categorySlug: "dentist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General & family dentistry"],
    languages: ["English", "Spanish", "French"],
    addressArea: "Eixample",
    bookingUrl: "https://www.elcedrobarcelona.com/en/english-speaking-dental-clinic/",
  },
  {
    id: "sarria-dentist-raslan",
    name: "Clínica Dental Raslan",
    categorySlug: "dentist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General dentistry"],
    languages: ["English", "Spanish", "Catalan"],
    addressArea: "Sarrià-Sant Gervasi, near La Bonanova",
    bookingUrl: "https://clinicaraslan.com/en/work-team/",
  },
  {
    id: "eixample-doctor-traveldoctores",
    name: "TravelDoctores (video consultations)",
    categorySlug: "doctor",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Video GP consultations"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample (online video consultations)",
    bookingUrl: "https://traveldoctores.com/doctor-in-barcelona-english-speaking/",
  },
  {
    id: "poblenou-psychologist-therapy-in-barcelona-el-clot",
    name: "Therapy in Barcelona: El Clot",
    categorySlug: "psychologist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Individual therapy", "Serves Poblenou & Sant Martí"],
    languages: ["English", "and other languages"],
    addressArea: "El Clot, near Poblenou",
    bookingUrl: "https://www.therapyinbarcelona.com/el-clot/",
  },
  {
    id: "sarria-psychologist-psicare",
    name: "PsIcare Health",
    categorySlug: "psychologist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Mental health clinic", "American-trained psychologists"],
    languages: ["English"],
    addressArea: "Sarrià-Sant Gervasi",
  },
  {
    id: "poblenou-dermatologist-english-doctor-barcelona",
    name: "English Doctor Barcelona",
    categorySlug: "dermatologist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Dermatology consultations", "Diagnostics & specialist referrals"],
    languages: ["English", "Spanish", "French", "Hindi", "Arabic"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://englishdoctorbarcelona.com",
  },
  {
    id: "eixample-dermatologist-saban",
    name: "Saban Dermatología",
    categorySlug: "dermatologist",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Clinical, surgical & cosmetic dermatology"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
  },
  {
    id: "eixample-fertility-reproclinic",
    name: "Reproclinic",
    categorySlug: "fertility-clinic",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["IVF", "Assisted reproduction"],
    languages: ["English", "Spanish", "Catalan", "French", "Italian", "German", "Dutch", "Portuguese"],
    addressArea: "Left Eixample, near Sant Antoni",
    bookingUrl: "https://www.fertilityclinicsabroad.com/clinics/reproclinic/",
  },
  {
    id: "les-corts-physiotherapist-mes",
    name: "MES Fisioterapia",
    categorySlug: "physiotherapist",
    areaSlug: "les-corts",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Physiotherapy", "Sports physiotherapy", "Osteopathy"],
    languages: ["English", "Spanish"],
    addressArea: "Les Corts",
    bookingUrl: "https://www.mesfisioterapia.com/home_en",
  },
  {
    id: "sarria-obgyn-turo-park",
    name: "Turó Park Clinics: Dr. Berta Esteban",
    categorySlug: "obgyn-midwife",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Gynaecology", "Gynaecological surgery"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/english-speaking-gynecologist-barcelona/",
  },
  {
    id: "sarria-obgyn-onbargi-teknon",
    name: "Dr. Leila Onbargi: Centro Médico Teknon",
    categorySlug: "obgyn-midwife",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Obstetrics", "Gynaecology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://www.barcelona-metropolitan.com/locations/centro-medico-teknon-Onbargi-gynecologist/",
  },
  {
    id: "poblenou-midwife-tribu-house",
    name: "Tribu House: Doula & Birth Support",
    categorySlug: "obgyn-midwife",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Doula support", "Birth & postpartum accompaniment"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://tribuhouse.com/en/services/acompanamiento-doula/",
  },
  {
    id: "sarria-pediatrician-turo-park",
    name: "Turó Park Medical Clinic",
    categorySlug: "pediatrician",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General pediatrics", "Diagnostics"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi",
    bookingUrl: "https://turoparkmedical.com/english-speaking-pediatrician/",
  },
  {
    id: "eixample-pediatrician-arcc",
    name: "Centro Pediátrico ARCC Barcelona",
    categorySlug: "pediatrician",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["General pediatrics", "Childhood allergies", "Pediatric traumatology"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample",
  },
  {
    id: "eixample-osteopath-malecot",
    name: "Malécot Osteopathy",
    categorySlug: "osteopath",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Adults", "Babies", "Pregnancy osteopathy"],
    languages: ["English", "French", "Spanish"],
    addressArea: "Eixample, near Plaça Universitat",
    bookingUrl: "https://malecotosteopatiabarcelona.com/en/",
  },
  {
    id: "gracia-osteopath-david-arbona",
    name: "David Arbona Osteopathy",
    categorySlug: "osteopath",
    areaSlug: "gracia",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Osteopathy"],
    languages: ["English", "Spanish"],
    addressArea: "Gràcia (also sees patients in Eixample)",
    bookingUrl: "https://davidarbona.com/en/david-arbona-osteopathy-in-barcelona/",
  },
  {
    id: "eixample-business-lawyer-forcam",
    name: "Forcam Lawyers",
    categorySlug: "business-lawyer",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Company formation", "Shareholder disputes", "Corporate maintenance"],
    languages: ["English", "Spanish"],
    addressArea: "Eixample, near Plaça Francesc Macià",
    bookingUrl: "https://www.forcamabogados.com/en/lawyers-barcelona",
  },
  {
    id: "sarria-orthodontist-turo-park",
    name: "Turó Park Clinics: Dr. Madeleine Smit",
    categorySlug: "orthodontist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign", "Lingual orthodontics", "Invisible braces"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/dental-clinic-barcelona/orthodontist/",
  },
  {
    id: "sarria-orthodontist-dental-spa",
    name: "Dental Spa Clinics",
    categorySlug: "orthodontist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign", "SureSmile", "Lingual orthodontics"],
    languages: ["English", "Spanish"],
    addressArea: "Carrer de Balmes, Sarrià-Sant Gervasi",
    bookingUrl: "https://dentalspaclinics.com/en/",
  },
  {
    id: "poblenou-orthodontist-maba",
    name: "MABA Odontología Avanzada",
    categorySlug: "orthodontist",
    areaSlug: "poblenou",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Invisalign clear aligners", "Orthodontic bite correction"],
    languages: ["English", "Spanish"],
    addressArea: "Poblenou, Sant Martí",
    bookingUrl: "https://www.mabadental.es/we-speak-english",
  },
  {
    id: "sarria-podiatrist-turo-park",
    name: "Turó Park Clinics: Podiatry",
    categorySlug: "podiatrist",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Biomechanics", "Ingrown toenail surgery", "Gait analysis"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/podiatrist-in-barcelona/",
  },
  {
    id: "sarria-eye-care-turo-park",
    name: "Turó Park Clinics: Ophthalmology",
    categorySlug: "eye-care",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Eye exams", "General ophthalmology"],
    languages: ["English", "Spanish"],
    addressArea: "Sarrià-Sant Gervasi, near Turó Park",
    bookingUrl: "https://turoparkmedical.com/medical-services/your-ophthalmologist-in-barcelona/",
  },
  {
    id: "sarria-insurance-inov-expat",
    name: "INOV Expat",
    categorySlug: "insurance-broker",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Health insurance", "Home insurance", "Car insurance"],
    languages: ["English", "French", "Spanish", "Portuguese", "Russian"],
    addressArea: "Via Augusta, Sant Gervasi",
    bookingUrl: "https://www.inovexpat.com/en/inov-expat-en/",
  },
  {
    id: "sarria-wealth-manager-w1m",
    name: "W1M",
    categorySlug: "wealth-manager",
    areaSlug: "sarria-sant-gervasi",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Expat wealth management", "Investment planning"],
    languages: ["English", "Spanish"],
    addressArea: "Ronda General Mitre, Sarrià-Sant Gervasi",
    bookingUrl: "https://www.w1m.com/individuals-families/expats-europe/",
  },
  {
    id: "eixample-notary-jla",
    name: "JLA Notarios",
    categorySlug: "notary",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property purchase signings", "Document certification"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    bookingUrl: "https://www.jlanotarios.com/en_GB/",
  },
  {
    id: "eixample-notary-benavides",
    name: "Notaría Jesús Benavides",
    categorySlug: "notary",
    areaSlug: "eixample",
    isPartner: false,
    isPlaceholder: false,
    specialties: ["Property purchase signings", "Power of attorney"],
    languages: ["English", "Spanish"],
    addressArea: "Avinguda Diagonal, Eixample",
    bookingUrl: "https://en.jesusbenavides.es/",
  },
];

// Used only on the internal /partners sales-preview page to show a prospective
// partner what their featured card will look like. Never rendered on public
// area/category pages.
export const exampleProfessional: Professional = {
  id: "example-preview",
  name: "Your Clinic Name",
  categorySlug: "dentist",
  areaSlug: "poblenou",
  isPartner: true,
  isPlaceholder: true,
  specialties: ["Implants", "Invisalign", "Cosmetic dentistry"],
  languages: ["English", "Spanish", "Catalan"],
  addressArea: "Poblenou, Barcelona",
  phoneDisplay: "+34 9XX XXX XXX",
  bookingUrl: "#",
  ratingLabel: "Recommended partner",
};

export function getProfessionals(areaSlug: string, categorySlug: string): Professional[] {
  return professionals
    .filter((p) => p.areaSlug === areaSlug && p.categorySlug === categorySlug)
    .sort((a, b) => Number(b.isPartner) - Number(a.isPartner));
}
